site_name: Boundless Exchange
theme: boundless
pages:
- Home: 'index.md'
- User Guide:
    - 'Log in to Exchange': 'user-guide/exchange-login.md'
    - 'Exchange Landing Page': 'user-guide/landing-page.md'
    - 'User Menu': 'user-guide/user-menu.md'
    - 'Explore Layers': 'user-guide/explore-layers.md'
    - 'Explore Maps': 'user-guide/explore-maps.md'
    - 'Explore Documents': 'user-guide/explore-documents.md'
    - 'Explore People': 'user-guide/explore-people.md'
    - 'Explore Groups': 'user-guide/explore-groups.md'
- About:
    - 'License': 'about/license.md'
    - 'Release Notes': 'about/release-notes.md'
